### ISSUE TITLE
Using Liquibase with Impala-Hive

### ISSUE THREAD

**Issue by carolhunt** [Datical/liquibase-docs#100]
Thank you for creating your article! Your work makes a huge impact on the Liquibase community. Below are the details we need in order to make your work accessible to the community and award points towards your status in the Liquibase Legends Program.

**URL to content**:
https://docs.liquibase.com/workflows/database-setup-tutorials/impala-hive.html

**Title**:
Using Liquibase with Impala-Hive

**Byline**:
Evgenii Seliavka

**Byline Link**: (Optional - We can link back your byline to a personal blog, social profile or Github profile) 
https://www.linkedin.com/in/eseliavka/

**Brief Summary of submission**: <ex. How to build a Maven artifact with liquibase changes>
process of creating a new Liquibase project for Impala/Hive

**LinkedIn**: (Optional- We’d like to add your picture with your byline!) 

Be sure to add labels that pertain to your content:
https://github.com/Datical/liquibase-docs/labels 

Thank you for your contribution! A member from our Community Team will review it.

┆Issue is synchronized with this [Jira Task](https://datical.atlassian.net/browse/PD-1392) by [Unito](https://www.unito.io/learn-more)

**Comment by eselyavka** [comment]
@carolhunt hello, ready to take the ticket.

**Comment by carolhunt** [comment]
Thanks, @eselyavka! I assigned the issue to you, and now closing the issue out so you can receive points towards Liquibase Legends! Thank you again for your contribution to our docs!
