### ISSUE TITLE
Using Liquibase with VoltDB

### ISSUE THREAD

**Issue by carolhunt** [Datical/liquibase-docs#101]
Thank you for creating your article! Your work makes a huge impact on the Liquibase community. Below are the details we need in order to make your work accessible to the community and award points towards your status in the Liquibase Legends Program.

**URL to content**:
https://docs.liquibase.com/workflows/database-setup-tutorials/voltdb.html

**Title**:
Using Liquibase with VoltDB

**Byline**:
Pavan Mulani

**Byline Link**: (Optional - We can link back your byline to a personal blog, social profile or Github profile) 

**Brief Summary of submission**: <ex. How to build a Maven artifact with liquibase changes>

**LinkedIn**: (Optional- We’d like to add your picture with your byline!) 

Be sure to add labels that pertain to your content:
https://github.com/Datical/liquibase-docs/labels 

Thank you for your contribution! A member from our Community Team will review it.

┆Issue is synchronized with this [Jira Task](https://datical.atlassian.net/browse/PD-1397) by [Unito](https://www.unito.io/learn-more)

**Comment by pavanmulani** [comment]
confirmed!

**Comment by carolhunt** [comment]
Thanks again for your contribution, Pavan! You'll see your point pop up in the next hour :)
