### ISSUE TITLE
Getting Started with Liquibase

### ISSUE THREAD

**Issue by carolhunt** [Datical/liquibase-docs#103]
Thank you for creating your article! Your work makes a huge impact on the Liquibase community. Below are the details we need in order to make your work accessible to the community and award points towards your status in the Liquibase Legends Program.

**URL to content**:
https://medium.com/podiihq/getting-started-with-liquibase-8965897092aa

**Title**:
Getting Started with Liquibase

**Byline**:
Maureen Josephine

**Byline Link**: (Optional - We can link back your byline to a personal blog, social profile or Github profile) 
https://medium.com/podiihq/getting-started-with-liquibase-8965897092aa

**Brief Summary of submission**: <ex. How to build a Maven artifact with liquibase changes>
How to get up and running with Liquibase

**LinkedIn**: (Optional- We’d like to add your picture with your byline!) 
https://www.linkedin.com/in/maureen-josephine-605127a9/ 

Be sure to add labels that pertain to your content:
https://github.com/Datical/liquibase-docs/labels 

Thank you for your contribution! A member from our Community Team will review it.

**Comment by JosephineAkello** [comment]
Confirmed, it was a pleasure writing the article

**Comment by carolhunt** [comment]
Thanks for your contribution @JosephineAkello!
