### ISSUE TITLE
What is Liquibase and how to start using it? Automate your database scripts deployment with this Liquibase tutorial

### ISSUE THREAD

**Issue by carolhunt** [Datical/liquibase-docs#113]
Thank you for creating your article! Your work makes a huge impact on the Liquibase community. Below are the details we need in order to make your work accessible to the community and award points towards your status in the Liquibase Legends Program.

**URL to content**:
https://pretius.com/liquibase-tutorial/

**Title**:
What is Liquibase and how to start using it? Automate your database scripts deployment with this Liquibase tutorial

**Byline**: 
Rafal Grzegorczyk 

**Byline Link**: (Optional - We can link back your byline to a personal blog, social profile or Github profile) 

**Brief Summary of submission**: Liquibase Tutorial 

Be sure to add labels that pertain to your content:
https://github.com/Datical/liquibase-docs/labels 

Thank you for your contribution! A member from our Community Team will review it.

**Comment by rgrzegorczyk** [comment]
No problem. More advanced tutorials in progress :)

**Comment by carolhunt** [comment]
Thanks, @rgrzegorczyk for your contribution! Your points should appear within the hour :)
