### ISSUE TITLE
Using Liquibase with Springboot

### ISSUE THREAD

**Issue by sohamda** [Datical/liquibase-docs#116]
Thank you for creating your article! Your work makes a huge impact on the Liquibase community. Below are the details we need in order to make your work accessible to the community and award points towards your status in the Liquibase Legends Program.

**URL to content**:
https://medium.com/springboot-chronicles/manage-database-changes-with-liquibase-in-spring-boot-256dbe156717

**Title**: Manage database changes with Liquibase in Spring Boot
**Byline**: 

**Byline Link**: (Optional - We can link back your byline to a personal blog, social profile or Github profile) 
https://github.com/sohamda/liquibase-h2
https://github.com/sohamda/liquibase-h2/tree/with-mysql-dependency

**Brief Summary of submission**: How to use Liquibase with Springboot a step-by-step guide

**LinkedIn**: (Optional- We’d like to add your picture with your byline!)  https://www.linkedin.com/in/dasguptasoham/

Be sure to add labels that pertain to your content: tutorial, community, written
https://github.com/Datical/liquibase-docs/labels 

Thank you for your contribution! A member from our Community Team will review it.

**Comment by carolhunt** [comment]
Hi @sohamda! Thank you for your submission! I have re-assigned to you (so you get the points!) and will close the issue. Again, a fantastic article and we appreciate your participating and contributions in the Liquibase Community!
