### ISSUE TITLE
Incorrect documentation link for "database changelog tables" on how liquibase works page

### ISSUE THREAD

**Issue by rakhi-agrawal** [Datical/liquibase-docs#153]
**Describe the bug**
In [getting started guide](https://www.liquibase.org/get-started/how-liquibase-works), help link for "databasechangelog table" takes us to "databasechangelog LOCK table" instead.

**To Reproduce**
1. Go to '[How Liquibase Works](https://www.liquibase.org/get-started/how-liquibase-works)'
2. Scroll down to "Tracking Tables"
3. Click on 'View the documentation on [DATABASECHANGELOG tables](https://docs.liquibase.com/concepts/databasechangelog-table.html?__hstc=128893969.b8b325f2c3a18a0fe19b01e7f62dd9a7.1653281030451.1653303824767.1653469544139.4&__hssc=128893969.8.1653469544139&__hsfp=3380253601&_ga=2.79039132.900196475.1653469255-2100443429.1653280992)'
4. See incorrect page

**Expected behavior**
The correct link should take you to : https://docs.liquibase.com/concepts/tracking-tables/databasechangelog-table.html

**Comment by adrian-velonis1** [comment]
Fixed https://github.com/Datical/liquibase-docs/commit/2715ae4356efebff226a7ada52b6320ad37d76e7
