### ISSUE TITLE
IncludeAll documentation mysterious

### ISSUE THREAD

**Issue by ari** [Datical/liquibase-docs#41]
Documentation here https://docs.liquibase.com/concepts/advanced/includeall.html suggests that include all will fail in mysterious ways when used like Rails with one changeset per file.

If includeAll is deprecated, then it should be marked as such. If it doesn't work in some situations, then this needs to be explained with less mystery. I'm not sure what danger I'm supposed to be avoiding here.

**Comment by mccormickc** [comment]
This topic has now been re-written and is merged to the staging site. Doc should go live within 24 hours. Thanks for making this report!!!
