### ISSUE TITLE
Tutorial: Using Liquibase with Impala/Hive

### ISSUE THREAD

**Issue by carolhunt** [Datical/liquibase-docs#46]
We need help creating a tutorial on using Liquibase with Impala/Hive

Below is some documentation I have found:
https://github.com/eselyavka/liquibase-impala

Below is link to the Liquibase Tutorial Template:
https://docs.google.com/document/d/1VWpbIVryiDvnaNROg5V1J_uUVJb9jzIAKSNUkHpFsVo/edit

Please utilize the template to aid in the flow of your work.

Your byline, photo and link to your preferred social page will be included once completed.

**Comment by mccormickc** [comment]
This document is now published to production
