### ISSUE TITLE
Documentation for Label

### ISSUE THREAD

**Issue by ro-rah** [Datical/liquibase-docs#51]
Please use the following as an example:
https://docsstage.liquibase.com/change-types/community/load-data.html

Please also include valid values as well as an example changesets in sql, xml, yaml, etc.

Please also include setting complex label statements in the commandline and how they get evaluated.
ex. I want to run a liquibase update on all available changesets with label rel5 and not perf

**Comment by mccormickc** [comment]
Documentation written and published to staging.
