### ISSUE TITLE
Document Using Multiple Schemas with Database Comparison Operations & generateChangeLog

### ISSUE THREAD

**Issue by ro-rah** [Datical/liquibase-docs#57]
Please use the following for format:
https://docsstage.liquibase.com/workflows/liquibase-community/multiple-sql-migration.html

**Comment by ro-rah** [comment]
This should be a document demonstrating a workflow where there is a need to work with multiple schemas in one changeLog.





1:22
For the diff ,diffChanegLog  , snapshot and generateChangeLog  portion of it, we can also introduce how to achieve this with the --schemas=schema1,shema2,schema3 combined with the --includeSchema=true flags.

**Comment by mccormickc** [comment]
Documentation merged
