### ISSUE TITLE
Document Changing a Line Delimiter

### ISSUE THREAD

**Issue by ro-rah** [Datical/liquibase-docs#58]
Please use the following as an example:
https://docsstage.liquibase.com/change-types/community/load-data.html

ex. changing to run multiple statements in say DB2

**Comment by ro-rah** [comment]
Here's a sample issue from the community:
https://forum.liquibase.org/t/oracle-end-delimiter-issue/730/2

**Comment by mccormickc** [comment]
Completed and published live!
