### ISSUE TITLE
Document runOnChange changeset attribute

### ISSUE THREAD

**Issue by ro-rah** [Datical/liquibase-docs#60]
Please use the following as an example:
https://docsstage.liquibase.com/change-types/community/load-data.html

**Comment by ro-rah** [comment]
https://docs.liquibase.com/concepts/basic/changeset.html
https://www.liquibase.org/get-started/best-practices (briefly mentions best prac when dealing with sprocs)

**Comment by mbohls** [comment]
https://docs.liquibase.com/change-types/community/create-procedure.html  (It is not clear if the applies to formatted sql changesets)

**Comment by mccormickc** [comment]
Documentation written and published to staging!
