### ISSUE TITLE
(Video) Workflow Tutorial: Rolling Back Changesets 

### ISSUE THREAD

**Issue by carolhunt** [Datical/liquibase-docs#66]
We need general workflow tutorials with step-by-step instructions on all of the different types of rollbacks used and when it is best to use them. It would be ideal to showcase in video form as well as written. 

We would like to improve the current documentation below:
https://docsstage.liquibase.com/workflows/liquibase-community/using-rollback.html

*The goal is to show how to perform them*

Below is a link to the workflow template:
https://docs.google.com/document/d/1Waz3_OPfQtSQ-WzGbP-hbQW9fFSxQgwS/edit

Please utilize the template to aid in the flow of your work.

Your byline, photo and link to your preferred social page will be included once completed.

**Comment by mccormickc** [comment]
Completed and published content. Closing ticket.
