### ISSUE TITLE
Using Liquibase with Spring Boot

### ISSUE THREAD

**Issue by carolhunt** [Datical/liquibase-docs#97]
Thank you for creating your article! Your work makes a huge impact on the Liquibase community. Below are the details we need in order to make your work accessible to the community and award points towards your status in the Liquibase Legends Program.

**URL to content**:
https://docs.liquibase.com/tools-integrations/springboot/springboot.html

**Title**:
Using Liquibase with Spring Boot

**Byline**: Julius Krah

**Byline Link**: (Optional - We can link back your byline to a personal blog, social profile or Github profile) 
https://juliuskrah.com/

**Brief Summary of submission**: <ex. How to build a Maven artifact with liquibase changes>
How to use Liquibase with Spring Boot

**LinkedIn**: (Optional- We’d like to add your picture with your byline!) 
https://www.linkedin.com/in/juliuskrah/

Be sure to add labels that pertain to your content:
https://github.com/Datical/liquibase-docs/labels 

Thank you for your contribution! A member from our Community Team will review it.

┆Issue is synchronized with this [Jira Task](https://datical.atlassian.net/browse/PD-1384) by [Unito](https://www.unito.io/learn-more)

**Comment by carolhunt** [comment]
Content approved towards Legends Program

**Comment by juliuskrah** [comment]
Confirmed

**Comment by carolhunt** [comment]
Thanks for your contribution, Julius! You should be seeing your points show up on the leaderboard in the next hour!
